### ISSUE TITLE
M2 - Agent

### ISSUE THREAD

**Issue by adamkral12** [adamkral12/PA165#47]
1. AgentDTO
2. AgentService/AgentServiceImpl - access agentDao
3. AgentFacade/AgentFacadeImpl - access agentDTO & agentService (mapping DAO - DTO via beanMappingService)

Examples of methods for service: getAgentsByMission, getAgentsByRank, getAgentsByCodeName, move agent to mission, remove from mission, remove from/add to department

**Comment by tremors0** [comment]
V Service (interface i implementace) zatím chybí metody: 

- List<Agent>getAgentsWithLanguageKnowledge(LanguageEnum language);
- List<Agent> getSoonRetiringAgents();

Interface je potřeba nastavit na public. V Service i implementaci jsou zbytečné importy (které jsem nejspíš způsobil já 😄).

V implementaci není ošetření vstupních parametrů.
